-- PostgreSQL target of the reviewed relational baseline; data import is separate.

CREATE TABLE posts (
    post_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author_id bigint NOT NULL,
    board_type VARCHAR(255) NOT NULL CHECK (board_type IN ('ADOPTION','COMMUNICATION','MISSING','PROTECTION','REPORT')),
    content text NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6) DEFAULT NULL,
    image_urls json DEFAULT NULL,
    title varchar(200) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (post_id)
);


CREATE TABLE comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author_id bigint NOT NULL,
    content text NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6) DEFAULT NULL,
    post_id bigint NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (comment_id)
);


CREATE TABLE outbox_events (
    outbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    aggregate_id varchar(255) NOT NULL,
    aggregate_type varchar(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    event_id varchar(255) NOT NULL,
    payload json NOT NULL,
    type varchar(255) NOT NULL,
    PRIMARY KEY (outbox_id),
    CONSTRAINT UK7ba1uqwbn85u1g6jg4ja1tk6k UNIQUE (event_id)
);


CREATE TABLE processed_events (
    event_id varchar(255) NOT NULL,
    event_type varchar(255) NOT NULL,
    processed_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (event_id)
);
