CREATE TABLE animal_reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    report_kind VARCHAR(16) NOT NULL CHECK (report_kind IN ('MISSING', 'SIGHTING')),
    description TEXT NOT NULL,
    image_urls JSON NOT NULL DEFAULT '[]',
    occurred_on DATE NOT NULL,
    approximate_time VARCHAR(40),
    region VARCHAR(120) NOT NULL,
    landmark VARCHAR(200),
    species VARCHAR(40) NOT NULL,
    animal_name VARCHAR(80),
    coat_color VARCHAR(100),
    animal_size VARCHAR(40),
    distinguishing_features VARCHAR(500),
    direction VARCHAR(200),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6)
);

CREATE INDEX animal_reports_kind_created_idx
    ON animal_reports(report_kind, created_at DESC, report_id DESC)
    WHERE deleted_at IS NULL;
