-- PostgreSQL target of the reviewed relational baseline; data import is separate.

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) DEFAULT NULL,
    updated_at TIMESTAMP(6) DEFAULT NULL,
    description varchar(500) DEFAULT NULL,
    name varchar(255) NOT NULL,
    parent_id bigint DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UKt8o6pivur7nn124jehx7cygw5 UNIQUE (name),
    CONSTRAINT FKsaok720gsu4u2wrgbk10b5n8d FOREIGN KEY (parent_id) REFERENCES categories (id)
);
CREATE INDEX FKsaok720gsu4u2wrgbk10b5n8d ON categories (parent_id);

CREATE TABLE option_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) DEFAULT NULL,
    updated_at TIMESTAMP(6) DEFAULT NULL,
    name varchar(50) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UK6h9l8ox1btal6pp5iov8of08j UNIQUE (name)
);


CREATE TABLE option_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) DEFAULT NULL,
    updated_at TIMESTAMP(6) DEFAULT NULL,
    name varchar(50) NOT NULL,
    option_group_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK88kn8vaj0u8kimku7mr1aq876 FOREIGN KEY (option_group_id) REFERENCES option_groups (id)
);
CREATE INDEX FK88kn8vaj0u8kimku7mr1aq876 ON option_values (option_group_id);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) DEFAULT NULL,
    updated_at TIMESTAMP(6) DEFAULT NULL,
    description text,
    image_url varchar(255) DEFAULT NULL,
    name varchar(100) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE','DELETED','HIDDEN','SOLD_OUT')),
    view_count bigint NOT NULL,
    category_id bigint DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FKog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES categories (id)
);
CREATE INDEX FKog2rp4qthbtt2lfyhfo32lsw9 ON products (category_id);

CREATE TABLE product_skus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) DEFAULT NULL,
    updated_at TIMESTAMP(6) DEFAULT NULL,
    price bigint NOT NULL,
    sku_code varchar(50) NOT NULL,
    stock_quantity int NOT NULL,
    product_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UK7j7kyn1tsyb9xlluxn1x62us0 UNIQUE (sku_code),
    CONSTRAINT FKgfjst7dvihycy15ceiruv9roo FOREIGN KEY (product_id) REFERENCES products (id)
);
CREATE INDEX FKgfjst7dvihycy15ceiruv9roo ON product_skus (product_id);

CREATE TABLE sku_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) DEFAULT NULL,
    updated_at TIMESTAMP(6) DEFAULT NULL,
    option_value_id bigint NOT NULL,
    product_sku_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FKcsjqyxps7l3diwdtk8i302db1 FOREIGN KEY (product_sku_id) REFERENCES product_skus (id),
    CONSTRAINT FKlcmx7bnd0imxqrxdaibisbt74 FOREIGN KEY (option_value_id) REFERENCES option_values (id)
);
CREATE INDEX FKlcmx7bnd0imxqrxdaibisbt74 ON sku_values (option_value_id);
CREATE INDEX FKcsjqyxps7l3diwdtk8i302db1 ON sku_values (product_sku_id);

CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) DEFAULT NULL,
    updated_at TIMESTAMP(6) DEFAULT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UK64t7ox312pqal3p7fg9o503c2 UNIQUE (user_id)
);


CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) DEFAULT NULL,
    updated_at TIMESTAMP(6) DEFAULT NULL,
    product_sku_id bigint NOT NULL,
    quantity int NOT NULL,
    sku_id bigint NOT NULL,
    cart_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FKpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES carts (id)
);
CREATE INDEX FKpcttvuq4mxppo8sxggjtn5i2c ON cart_items (cart_id);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) DEFAULT NULL,
    updated_at TIMESTAMP(6) DEFAULT NULL,
    delivery_address varchar(255) NOT NULL,
    delivery_message varchar(200) DEFAULT NULL,
    delivery_status VARCHAR(20) NOT NULL CHECK (delivery_status IN ('DELIVERED','READY','SHIPPING')),
    order_uuid varchar(36) NOT NULL,
    receiver_name varchar(50) NOT NULL,
    receiver_phone varchar(20) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('CANCELLED','COMPLETED','FAILED','PAID','PENDING')),
    total_amount bigint NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UKphq8jmop0gyemsbhiwtg2lk6l UNIQUE (order_uuid)
);


CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) DEFAULT NULL,
    updated_at TIMESTAMP(6) DEFAULT NULL,
    price bigint NOT NULL,
    product_name varchar(100) NOT NULL,
    quantity int NOT NULL,
    sku_code varchar(50) NOT NULL,
    order_id bigint NOT NULL,
    product_sku_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK6yk0kr9ex98qxa222uyh7yw4h FOREIGN KEY (product_sku_id) REFERENCES product_skus (id),
    CONSTRAINT FKbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES orders (id)
);
CREATE INDEX FKbioxgbv59vetrxe0ejfubep1w ON order_items (order_id);
CREATE INDEX FK6yk0kr9ex98qxa222uyh7yw4h ON order_items (product_sku_id);

CREATE TABLE outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    aggregate_id varchar(100) NOT NULL,
    aggregate_type varchar(50) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    event_type varchar(50) NOT NULL,
    payload json NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE wishlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) DEFAULT NULL,
    updated_at TIMESTAMP(6) DEFAULT NULL,
    user_id bigint NOT NULL,
    sku_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK2al13a9l2fysctnic3uluhh0a FOREIGN KEY (sku_id) REFERENCES product_skus (id)
);
CREATE INDEX FK2al13a9l2fysctnic3uluhh0a ON wishlists (sku_id);
