-- Fresh PostgreSQL schema, derived from the reviewed MySQL V1-V7 tables.
-- Separate Flyway location/history: never edit or replay the MySQL migrations.
-- Existing LocalDateTime values retain timestamp(6) without time zone semantics.
-- Identity values imported explicitly require sequence reseeding before new writes.
-- Text equality/collation and production query compatibility need separate validation.

CREATE TABLE shelters (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp(6) without time zone NOT NULL,
  updated_at timestamp(6) without time zone DEFAULT NULL,
  address varchar(500) DEFAULT NULL,
  adoption_procedure varchar(2000) DEFAULT NULL,
  care_reg_no varchar(50) NOT NULL,
  email varchar(100) DEFAULT NULL,
  introduction varchar(2000) DEFAULT NULL,
  name varchar(200) NOT NULL,
  operating_hours varchar(200) DEFAULT NULL,
  organization_name varchar(200) DEFAULT NULL,
  owner_name varchar(100) DEFAULT NULL,
  phone varchar(50) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT idx_care_reg_no UNIQUE (care_reg_no)
);
CREATE TABLE animals (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp(6) without time zone NOT NULL,
  updated_at timestamp(6) without time zone DEFAULT NULL,
  api_source varchar(32) CHECK (api_source IN ('APMS_ANIMAL','GYEONGGI','MANUAL','UNKNOWN')) NOT NULL,
  apms_desertion_no varchar(50) DEFAULT NULL,
  apms_notice_no varchar(100) NOT NULL,
  apms_process_state varchar(50) DEFAULT NULL,
  apms_updated_at timestamp(6) without time zone DEFAULT NULL,
  birth_year int DEFAULT NULL,
  breed varchar(100) DEFAULT NULL,
  color varchar(100) DEFAULT NULL,
  description varchar(2000) DEFAULT NULL,
  favorite_count int NOT NULL,
  gender varchar(32) CHECK (gender IN ('FEMALE','MALE','UNKNOWN')) NOT NULL,
  happen_date date DEFAULT NULL,
  happen_place varchar(200) DEFAULT NULL,
  image_url varchar(500) DEFAULT NULL,
  image_url2 varchar(500) DEFAULT NULL,
  neuter_status varchar(32) CHECK (neuter_status IN ('NO','UNKNOWN','YES')) NOT NULL,
  notice_end_date date NOT NULL,
  notice_start_date date NOT NULL,
  special_mark varchar(1000) DEFAULT NULL,
  species varchar(32) CHECK (species IN ('CAT','DOG','ETC')) NOT NULL,
  status varchar(32) CHECK (status IN ('ADOPTED','ADOPTION_PENDING','DONATED','ESCAPED','EUTHANIZED','NATURAL_DEATH','NOTICE','PROTECT','RELEASED','RETURNED','UNKNOWN')) NOT NULL,
  weight varchar(50) DEFAULT NULL,
  shelter_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT idx_apms_desertion_no UNIQUE (apms_desertion_no),
  CONSTRAINT FK7fmlpw3o4ourhtv3qy8gl6cn5 FOREIGN KEY (shelter_id) REFERENCES shelters (id)
);
CREATE INDEX idx_species_status ON animals (species,status);
CREATE INDEX idx_notice_end_date ON animals (notice_end_date);
CREATE INDEX idx_shelter_id ON animals (shelter_id);
CREATE INDEX idx_apms_notice_no ON animals (apms_notice_no);
CREATE TABLE sync_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  api_source varchar(32) CHECK (api_source IN ('APMS_ANIMAL','GYEONGGI','MANUAL','UNKNOWN')) NOT NULL,
  end_time timestamp(6) without time zone DEFAULT NULL,
  error_message text,
  fail_count int NOT NULL,
  start_time timestamp(6) without time zone NOT NULL,
  success_count int NOT NULL,
  sync_status varchar(32) CHECK (sync_status IN ('FAIL','IN_PROGRESS','PARTIAL_SUCCESS','SUCCESS')) NOT NULL,
  total_count int DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE processed_events (
  event_id varchar(50) NOT NULL,
  event_type varchar(50) NOT NULL,
  processed_at timestamp(6) without time zone NOT NULL,
  PRIMARY KEY (event_id)
);
CREATE INDEX idx_processed_at ON processed_events (processed_at);
CREATE TABLE outbox_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  aggregate_id varchar(50) NOT NULL,
  aggregate_type varchar(50) NOT NULL,
  created_at timestamp(6) without time zone NOT NULL,
  event_id varchar(50) NOT NULL,
  event_type varchar(50) NOT NULL,
  payload text NOT NULL,
  topic varchar(100) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UK7ba1uqwbn85u1g6jg4ja1tk6k UNIQUE (event_id)
);
CREATE INDEX idx_outbox_created_at ON outbox_events (created_at);
CREATE TABLE chatbot_sessions (
  id varchar(36) NOT NULL,
  anonymous_session_id varchar(36) NOT NULL,
  animal_id bigint NOT NULL,
  created_at timestamp(6) without time zone NOT NULL,
  updated_at timestamp(6) without time zone DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_chatbot_sessions_animal FOREIGN KEY (animal_id) REFERENCES animals (id)
);
CREATE INDEX idx_chatbot_sessions_anon_animal ON chatbot_sessions (anonymous_session_id,animal_id);
CREATE INDEX fk_chatbot_sessions_animal ON chatbot_sessions (animal_id);
CREATE TABLE chatbot_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  session_id varchar(36) NOT NULL,
  role varchar(20) NOT NULL,
  content varchar(1000) NOT NULL,
  provider varchar(50) DEFAULT NULL,
  safety_notice varchar(500) DEFAULT NULL,
  created_at timestamp(6) without time zone NOT NULL,
  updated_at timestamp(6) without time zone DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_chatbot_messages_session FOREIGN KEY (session_id) REFERENCES chatbot_sessions (id)
);
CREATE INDEX idx_chatbot_messages_session_created ON chatbot_messages (session_id,created_at);
CREATE TABLE chatbot_block_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  animal_id bigint NOT NULL,
  anonymous_session_id varchar(36) NOT NULL,
  ip_hash varchar(64) NOT NULL,
  category varchar(50) NOT NULL,
  reason varchar(100) NOT NULL,
  question_length int NOT NULL,
  question_preview varchar(200) DEFAULT NULL,
  created_at timestamp(6) without time zone NOT NULL,
  updated_at timestamp(6) without time zone DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_chatbot_block_logs_animal FOREIGN KEY (animal_id) REFERENCES animals (id)
);
CREATE INDEX idx_chatbot_block_logs_anon_created ON chatbot_block_logs (anonymous_session_id,created_at);
CREATE INDEX idx_chatbot_block_logs_ip_created ON chatbot_block_logs (ip_hash,created_at);
CREATE INDEX fk_chatbot_block_logs_animal ON chatbot_block_logs (animal_id);
-- Provider metadata and published snapshots; no photo binaries are stored here.
CREATE TABLE pet_travel_regions (
    code VARCHAR(5) NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    fetched_at timestamp(6) without time zone NOT NULL,
    completed_at timestamp(6) without time zone NULL
);

CREATE TABLE pet_travel_collection_state (
    id SMALLINT NOT NULL PRIMARY KEY,
    phase VARCHAR(16) NOT NULL,
    next_page INT NOT NULL,
    error_code VARCHAR(32) NULL,
    completed_at timestamp(6) without time zone NULL
);
INSERT INTO pet_travel_collection_state(id,phase,next_page) VALUES (1,'HIDDEN',1);

CREATE TABLE pet_travel_collection_runs (
    id CHAR(36) NOT NULL PRIMARY KEY,
    started_at timestamp(6) without time zone NOT NULL,
    finished_at timestamp(6) without time zone NULL,
    status VARCHAR(16) NOT NULL,
    requests INT NOT NULL DEFAULT 0,
    discovered INT NOT NULL DEFAULT 0,
    published INT NOT NULL DEFAULT 0,
    error_code VARCHAR(32) NULL
);

CREATE TABLE pet_travel_request_budgets (
    request_day DATE NOT NULL,
    operation VARCHAR(32) NOT NULL,
    used INT NOT NULL,
    PRIMARY KEY(request_day,operation)
);

-- A durable work list exists independently of a published place.
CREATE TABLE pet_travel_targets (
    provider VARCHAR(32) NOT NULL,
    content_id VARCHAR(20) NOT NULL,
    area_code VARCHAR(5) NULL,
    modified_time CHAR(14) NOT NULL,
    shown BOOLEAN NOT NULL,
    image_url VARCHAR(2048) NULL,
    copyright_type VARCHAR(16) NULL,
    generation BIGINT NOT NULL,
    pending BOOLEAN NOT NULL,
    observed_at timestamp(6) without time zone NOT NULL,
    PRIMARY KEY (provider, content_id)
);
CREATE INDEX idx_travel_pending ON pet_travel_targets (pending, observed_at, content_id);
CREATE INDEX idx_travel_region_pending ON pet_travel_targets (area_code, pending);

CREATE TABLE pet_travel_places (
    provider VARCHAR(32) NOT NULL,
    content_id VARCHAR(20) NOT NULL,
    area_code VARCHAR(5) NOT NULL,
    title VARCHAR(500) NOT NULL,
    common_data JSONB NOT NULL,
    pet_data JSONB NOT NULL,
    image_url VARCHAR(2048) NULL,
    copyright_type VARCHAR(16) NULL,
    visible BOOLEAN NOT NULL,
    published_at timestamp(6) without time zone NOT NULL,
    PRIMARY KEY (provider, content_id)
);
CREATE INDEX idx_travel_public_region ON pet_travel_places (area_code, visible, title, content_id);

-- Keep V2 snapshots intact; discovery can now serve basic data before detail enrichment.
ALTER TABLE pet_travel_targets
    ADD COLUMN basic_data JSONB NULL,
    ADD COLUMN basic_fetched_at timestamp(6) without time zone NULL,
    ADD COLUMN detail_attempted_at timestamp(6) without time zone NULL,
    ADD COLUMN detail_error VARCHAR(32) NULL;

-- Old DETAILS checkpoints must not prevent future discovery scans.
UPDATE pet_travel_collection_state SET phase='HIDDEN',next_page=1 WHERE phase='DETAILS';

CREATE TABLE apms_photo_scan (
  id SMALLINT PRIMARY KEY,
  new_cursor BIGINT NOT NULL,
  sweep_cursor BIGINT NOT NULL
);

CREATE TABLE apms_photo_archive (
  animal_id BIGINT NOT NULL,
  slot SMALLINT NOT NULL,
  desertion_no VARCHAR(50) NOT NULL,
  source_url VARCHAR(500) NULL,
  generation BIGINT NOT NULL DEFAULT 1,
  state VARCHAR(16) NOT NULL,
  attempts INT NOT NULL DEFAULT 0,
  next_attempt_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  lease_token VARCHAR(36) NULL,
  lease_until timestamp(6) without time zone NULL,
  error_code VARCHAR(64) NULL,
  archived_source_url VARCHAR(500) NULL,
  source_sha256 CHAR(64) NULL,
  stored_sha256 CHAR(64) NULL,
  object_key VARCHAR(200) NULL,
  content_type VARCHAR(32) NULL,
  stored_bytes INT NULL,
  width INT NULL,
  height INT NULL,
  recipe VARCHAR(64) NULL,
  archived_at timestamp(6) without time zone NULL,
  PRIMARY KEY (animal_id, slot),
  CONSTRAINT fk_photo_animal FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE,
  CONSTRAINT chk_photo_slot CHECK (slot IN (1,2))
);
CREATE INDEX idx_photo_due ON apms_photo_archive (state, next_attempt_at);
CREATE INDEX idx_photo_lease ON apms_photo_archive (state, lease_until);

CREATE TABLE shelter_public_information (
  shelter_id BIGINT NOT NULL,
  details JSONB NOT NULL,
  collected_at timestamp(6) without time zone NOT NULL,
  PRIMARY KEY (shelter_id),
  CONSTRAINT fk_shelter_public_information FOREIGN KEY (shelter_id) REFERENCES shelters(id) ON DELETE CASCADE
);

-- Independent pet conditions: common-detail failures must not block these snapshots.
ALTER TABLE pet_travel_targets
    ADD COLUMN pet_valid_after timestamp(6) without time zone NULL,
    ADD COLUMN pet_changed_at timestamp(6) without time zone NULL;

CREATE TABLE pet_travel_pet_details (
    provider VARCHAR(32) NOT NULL,
    content_id VARCHAR(20) NOT NULL,
    pet_data JSONB NOT NULL,
    source VARCHAR(16) NOT NULL,
    fetched_at timestamp(6) without time zone NOT NULL,
    valid_until timestamp(6) without time zone NULL,
    cycle_id CHAR(36) NULL,
    PRIMARY KEY (provider, content_id)
);

INSERT INTO pet_travel_pet_details(provider,content_id,pet_data,source,fetched_at)
SELECT provider,content_id,pet_data,'LEGACY',published_at FROM pet_travel_places WHERE visible=TRUE;

CREATE TABLE pet_travel_pet_collection_state (
    id SMALLINT NOT NULL PRIMARY KEY,
    next_page INT NOT NULL,
    expected_total INT NULL,
    cycle_id CHAR(36) NOT NULL,
    completed_at timestamp(6) without time zone NULL,
    error_code VARCHAR(32) NULL
);
INSERT INTO pet_travel_pet_collection_state(id,next_page,cycle_id) VALUES (1,1,gen_random_uuid()::text);

-- Type-specific visit information and provider-hosted gallery photos.
-- Each resource keeps its own source revision so one failed endpoint does not
-- invalidate or repeatedly refetch the other successful resources.
CREATE TABLE pet_travel_visit_details (
    provider VARCHAR(32) NOT NULL,
    content_id VARCHAR(20) NOT NULL,
    content_type_id VARCHAR(2) NOT NULL,
    intro_data JSONB NULL,
    info_data JSONB NULL,
    intro_source_modified_time CHAR(14) NULL,
    info_source_modified_time CHAR(14) NULL,
    image_source_modified_time CHAR(14) NULL,
    intro_fetched_at timestamp(6) without time zone NULL,
    info_fetched_at timestamp(6) without time zone NULL,
    image_fetched_at timestamp(6) without time zone NULL,
    intro_attempted_at timestamp(6) without time zone NULL,
    info_attempted_at timestamp(6) without time zone NULL,
    image_attempted_at timestamp(6) without time zone NULL,
    intro_error VARCHAR(32) NULL,
    info_error VARCHAR(32) NULL,
    image_error VARCHAR(32) NULL,
    PRIMARY KEY (provider, content_id)
);
CREATE INDEX idx_travel_visit_intro ON pet_travel_visit_details (intro_attempted_at, content_id);
CREATE INDEX idx_travel_visit_info ON pet_travel_visit_details (info_attempted_at, content_id);
CREATE INDEX idx_travel_visit_image ON pet_travel_visit_details (image_attempted_at, content_id);

CREATE TABLE pet_travel_images (
    provider VARCHAR(32) NOT NULL,
    content_id VARCHAR(20) NOT NULL,
    serial_number VARCHAR(32) NOT NULL,
    image_name VARCHAR(500) NULL,
    original_url VARCHAR(2048) NOT NULL,
    thumbnail_url VARCHAR(2048) NULL,
    copyright_type VARCHAR(16) NULL,
    display_order INT NOT NULL,
    fetched_at timestamp(6) without time zone NOT NULL,
    PRIMARY KEY (provider, content_id, serial_number)
);
CREATE INDEX idx_travel_images_display ON pet_travel_images (provider, content_id, display_order);
