-- Reviewed PostgreSQL target; data transfer and identity sequence alignment are separate.
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    care_reg_no VARCHAR(50), created_at TIMESTAMP(6),
    email VARCHAR(255) NOT NULL, name VARCHAR(20) NOT NULL,
    nickname VARCHAR(30) NOT NULL, password VARCHAR(255),
    provider VARCHAR(20) NOT NULL, provider_id VARCHAR(100),
    role VARCHAR(20) NOT NULL CHECK (role IN ('ROLE_ADMIN','ROLE_SHELTER','ROLE_USER')),
    updated_at TIMESTAMP(6),
    UNIQUE (email, provider), UNIQUE (nickname)
);
-- Preserve case-insensitive account uniqueness while keeping display spelling.
CREATE UNIQUE INDEX uk_users_email_provider_folded ON users (lower(email), lower(provider));
CREATE UNIQUE INDEX uk_users_nickname_folded ON users (lower(nickname));
CREATE TABLE favorites (
    favorite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id BIGINT NOT NULL, created_at TIMESTAMP(6) NOT NULL, user_id BIGINT NOT NULL,
    CONSTRAINT uk_user_animal UNIQUE (user_id, animal_id),
    CONSTRAINT fk_favorites_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE RESTRICT
);
CREATE INDEX idx_favorite_animal_id ON favorites (animal_id);
CREATE TABLE outbox_events (
    outbox_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id VARCHAR(100) NOT NULL, aggregate_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL, event_id VARCHAR(36) NOT NULL UNIQUE,
    event_type VARCHAR(50) NOT NULL, payload JSON NOT NULL, topic VARCHAR(100) NOT NULL
);
CREATE INDEX idx_outbox_created_at ON outbox_events (created_at);
CREATE TABLE processed_events (
    event_id VARCHAR(36) PRIMARY KEY, event_type VARCHAR(50) NOT NULL, processed_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX idx_processed_at ON processed_events (processed_at);
CREATE TABLE refresh_tokens (
    refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL, expires_at TIMESTAMP(6) NOT NULL,
    token VARCHAR(500) NOT NULL UNIQUE, user_id BIGINT NOT NULL
);
CREATE TABLE shelter_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL,
    shelter_name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING','APPROVED','REJECTED')),
    requested_at TIMESTAMP(6) NOT NULL, reviewed_by BIGINT, reviewed_at TIMESTAMP(6),
    review_note VARCHAR(1000), care_reg_no VARCHAR(50)
);
-- Same contract as MySQL generated pending_user_id: only one pending request per user.
CREATE UNIQUE INDEX uk_shelter_application_pending_user ON shelter_applications (user_id) WHERE status = 'PENDING';
CREATE INDEX idx_shelter_application_user ON shelter_applications (user_id, id);
CREATE INDEX idx_shelter_application_status ON shelter_applications (status, id);
