-- Payment identifiers and historical timestamps are preserved; no payment provider calls.
CREATE TABLE outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id VARCHAR(100) NOT NULL, aggregate_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL, event_type VARCHAR(50) NOT NULL, payload JSON NOT NULL
);
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6), updated_at TIMESTAMP(6), amount BIGINT NOT NULL,
    approved_at TIMESTAMP(6), method VARCHAR(20), order_id VARCHAR(36) NOT NULL,
    payment_key VARCHAR(100) NOT NULL UNIQUE, requested_at TIMESTAMP(6),
    status VARCHAR(20) NOT NULL CHECK (status IN ('ABORTED','CANCELED','DONE','READY')),
    user_id BIGINT NOT NULL
);
